#!/bin/bash
#
# chkconfig: 35 90 12
# description: Condor startd
#
# Get function from functions library
#. /etc/init.d/functions
# Start the daemon
stat=0

start() {
        echo -n "Starting condor_negotiator: "
        if [ -e /var/lock/condor_negotiator ]
        then
          echo -n "condor_negotiator already running"
        else
          touch /var/lock/condor_negotiator
          /usr/sbin/condor_negotiator &
          echo -n "condor_negotiator started successfully"
        fi
        echo
}
# Stop the service
stop() {
        echo -n "Stopping condor_negotiator: "
        pkill condor_negotiator
        ### Now, delete the lock file ###
        rm -f /var/lock/condor_negotiator
        echo -n "condor_negotiator stopped successfully"
        echo
}
status() {
        pidof condor_negotiator
        if [ $? -ne 0 ]
        then
          echo -n "condor_negotiator is not running, "
          stat=1
        else
          echo -n "condor_negotiator is running, "
        fi

        if [ -e /var/lock/condor_negotiator ]
        then
          echo -n "lockfile present"
        else
          echo -n "lockfile not present"
        fi
        
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit $stat
